//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MattersQFORECLOSUR6
    {
        public string MattersQFORECLOSUR61 { get; set; }
        public string MattersQFORECLOSUREPRO { get; set; }
        public Nullable<System.DateTime> AddingDateTime { get; set; }
        public Nullable<int> CascadeOrder { get; set; }
        public Nullable<System.DateTime> QTOTITLEREQDATE { get; set; }
        public Nullable<System.DateTime> QTOTITLERECVDDATE { get; set; }
        public string QTOTITLETYPE { get; set; }
        public string QTOTITLEPROVIDER { get; set; }
        public Nullable<System.DateTime> QTOTITLEEFFECTDATE { get; set; }
        public Nullable<System.DateTime> QTOTITLERPTTOCLIENT { get; set; }
        public Nullable<System.DateTime> QTOTITLEEXAMDATE { get; set; }
        public Nullable<System.DateTime> QTOTITLEAPPROVED { get; set; }
        public Nullable<int> TITL_Order_OrderID { get; set; }
        public Nullable<System.DateTime> TITL_Order_ExamOnlyTriggered { get; set; }
        public string QTOTITLERUSH { get; set; }
        public string QTONOTES { get; set; }
    }
}
