//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matters
    {
        public string Matters1 { get; set; }
        public string MatterID { get; set; }
        public string ShortDesc { get; set; }
        public string AreaOfLaw { get; set; }
        public string MatterType { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public string ClientSort { get; set; }
        public string MatterIDSort { get; set; }
        public string ClientPronoun { get; set; }
        public string OpposingPronoun { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.DateTime> Entered { get; set; }
        public string Rates { get; set; }
        public string Tasks { get; set; }
        public string StmnFormats { get; set; }
        public string PreBillStmnFormats { get; set; }
        public string BillFreq { get; set; }
        public string AddingProfessionals { get; set; }
        public Nullable<System.DateTime> AddingDateTime { get; set; }
        public Nullable<decimal> FirmPercentage { get; set; }
        public Nullable<decimal> BudgetFees { get; set; }
        public Nullable<decimal> BudgetHours { get; set; }
        public Nullable<decimal> BudgetHardCosts { get; set; }
        public Nullable<decimal> BudgetSoftCosts { get; set; }
        public string WDFees { get; set; }
        public string WDHardCosts { get; set; }
        public string WDSoftCosts { get; set; }
        public Nullable<decimal> PeriodicRetainer { get; set; }
        public string StmnRTF { get; set; }
        public string EventTypeRules { get; set; }
        public string EventTypeRules2 { get; set; }
        public string SecurityGroupView { get; set; }
        public string SecurityGroupChange { get; set; }
        public string SecurityGroupDelete { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string IsReverseView { get; set; }
        public Nullable<int> BillingGroup { get; set; }
        public string ClientID { get; set; }
        public string ClientIDSort { get; set; }
        public string SecurityGroupPortalView { get; set; }
        public string SettlementStmnFormats { get; set; }
        public string SettleTrustAccounts { get; set; }
        public string SettleCashAccounts { get; set; }
        public int WFStatus { get; set; }
        public string IsApplySecurity { get; set; }
        public string BillFreqCosts { get; set; }
        public string MatterNum { get; set; }
        public string SubMatterNum { get; set; }
        public int ClosingWFStatus { get; set; }
        public string ILSKey { get; set; }
        public string QSUBAREAOFLAW { get; set; }
        public Nullable<System.DateTime> QFORECLOSURESAL { get; set; }
        public Nullable<System.DateTime> QDATEREFERRED { get; set; }
        public string QWELLSBKASSOCIA { get; set; }
        public string QLITIGATIONATTO { get; set; }
        public string QLASTFOURDIGITS { get; set; }
        public string QNONBILLABLESTA { get; set; }
        public Nullable<int> LpsNTRID { get; set; }
        public Nullable<System.DateTime> LpsDocumentDate { get; set; }
        public string QLPSPROCESSNAME { get; set; }
        public Nullable<System.DateTime> LpsDocumentAttemptDate { get; set; }
        public Nullable<int> LpsDocumentAttemptCount { get; set; }
        public string QWELLSSOURCE { get; set; }
        public string QLPSSERVICERNAM { get; set; }
        public Nullable<System.DateTime> LpsDocsRecovered { get; set; }
        public Nullable<System.DateTime> LpsDocsRecoveryAttempted { get; set; }
        public string NetDirectorCaseId { get; set; }
        public string QFROMTHISMATTER { get; set; }
        public string QFORECLOSURESTA { get; set; }
        public string QTITLECURATIVES { get; set; }
        public string QREOSTATUS { get; set; }
        public string QDISPOSITIONOFR2 { get; set; }
        public Nullable<System.DateTime> QPNMACREFERRALR { get; set; }
        public Nullable<System.DateTime> QBARDATEVERIFIE { get; set; }
        public Nullable<System.DateTime> QACQUISITIONDAT { get; set; }
        public string QMATTERKEYWORD { get; set; }
        public string QSPECIALPROJECT { get; set; }
        public string QBUDGETCONTROL { get; set; }
    }
}
