//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MattersQFORECLOSUR5
    {
        public string MattersQFORECLOSUR51 { get; set; }
        public string MattersQFORECLOSUREPRO { get; set; }
        public Nullable<System.DateTime> AddingDateTime { get; set; }
        public Nullable<int> CascadeOrder { get; set; }
        public Nullable<System.DateTime> QTIRFEDTAXLIEN { get; set; }
        public string QTIRFEDTAXLIENPROF { get; set; }
        public Nullable<System.DateTime> QTIRDELQTAXES { get; set; }
        public string QTIRDELQTAXESPROF { get; set; }
        public Nullable<System.DateTime> QTIRTITLEDEF { get; set; }
        public string QTIRTITLEDEFPROF { get; set; }
        public Nullable<System.DateTime> QTIRTCREQUESTED { get; set; }
        public string QTIRTCREQUESTEDPROF { get; set; }
        public Nullable<System.DateTime> QTIRTCPROCASS { get; set; }
        public string QTIRTCPROCASSPROF { get; set; }
        public Nullable<System.DateTime> QTIRPASS { get; set; }
        public Nullable<System.DateTime> QTIRDUPLICATE { get; set; }
        public Nullable<System.DateTime> QTIRFCCLOSED { get; set; }
        public string QTIRTCPROCPASS { get; set; }
        public string QTIRTCPROCDUP { get; set; }
        public string QTCPROCFCCLOSE { get; set; }
    }
}
