//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MattersQFORECLOSUREPRO
    {
        public string MattersQFORECLOSUREPRO1 { get; set; }
        public string Matters { get; set; }
        public Nullable<System.DateTime> QASSIGNMENTORDE { get; set; }
        public Nullable<System.DateTime> QASSIGNMENTRECE { get; set; }
        public Nullable<System.DateTime> QASSIGNMENTSENT { get; set; }
        public Nullable<System.DateTime> QFDCPALETTERSEN { get; set; }
        public Nullable<System.DateTime> QFTLNOTICE { get; set; }
        public Nullable<System.DateTime> QHUDOCCLETTER { get; set; }
        public Nullable<System.DateTime> QNOICEOFPENDING { get; set; }
        public Nullable<System.DateTime> QPUBLICATIONDAT { get; set; }
        public string QSALEMONTH { get; set; }
        public Nullable<System.DateTime> QSUBLIENNOTICE { get; set; }
        public Nullable<System.DateTime> QTEAMTITLEREVIE { get; set; }
        public Nullable<System.DateTime> QTITLEEXAMORDER { get; set; }
        public Nullable<System.DateTime> QTITLEEXAMRECEI { get; set; }
        public string QSALEYEAR { get; set; }
        public Nullable<System.DateTime> QTITLEAPPROVEDF { get; set; }
        public Nullable<System.DateTime> QVAAPPRAISALCOM { get; set; }
        public Nullable<System.DateTime> QVAAPPRAISALORD { get; set; }
        public Nullable<System.DateTime> QHUDFIRSTACTION { get; set; }
        public Nullable<System.DateTime> QWELLSPRESALECH { get; set; }
        public Nullable<System.DateTime> QFDCPADATAVALID { get; set; }
        public Nullable<System.DateTime> QNOSDATAVALIDAT { get; set; }
        public Nullable<System.DateTime> QFNMALETTERSENT { get; set; }
        public Nullable<System.DateTime> QBREACHLETTERSE { get; set; }
        public Nullable<System.DateTime> QBREACHLETTEREX { get; set; }
        public Nullable<System.DateTime> QWELLS10DAYCHEC { get; set; }
        public Nullable<System.DateTime> QCHASELETTERSEN { get; set; }
        public Nullable<System.DateTime> QNOTEREVIEWED { get; set; }
        public string QREBREACHNEEDED { get; set; }
        public Nullable<System.DateTime> QVALIDBREACHLET { get; set; }
        public Nullable<decimal> QREBREACHAMOUNT { get; set; }
        public Nullable<System.DateTime> QREBREACHFEEAPP { get; set; }
        public Nullable<System.DateTime> QREBREACHREINST { get; set; }
        public string QCORRECTIVEASSI { get; set; }
        public Nullable<System.DateTime> QCORRECTIVEASSI2 { get; set; }
        public Nullable<System.DateTime> QCORRECTIVEASSI23 { get; set; }
        public Nullable<System.DateTime> QCORRECTIVEASSI234 { get; set; }
        public string QFTLNOTICENEEDE { get; set; }
        public string QTYPEOFASSIGNME { get; set; }
        public Nullable<System.DateTime> QADPUBLICATIONC { get; set; }
        public Nullable<System.DateTime> QADRECEIPTCONFI { get; set; }
        public Nullable<System.DateTime> QADREVIEWED { get; set; }
        public Nullable<System.DateTime> QADSUBMITTED { get; set; }
        public Nullable<System.DateTime> QBIDREVIEWEDUPL { get; set; }
        public Nullable<System.DateTime> QHAMPCERTIFICAT { get; set; }
        public string QSALEPOSTPONEDR { get; set; }
        public string QSALERESCINDREA { get; set; }
        public string QSALESTOPPEDREA { get; set; }
        public string QSOLDTO { get; set; }
        public Nullable<System.DateTime> QBIDINSTRUCTION { get; set; }
        public string QDOCUMENTSNEEDE { get; set; }
        public Nullable<System.DateTime> QREESEREVIEWCOM { get; set; }
        public Nullable<System.DateTime> QTITLEEXAMTOCLI { get; set; }
        public Nullable<System.DateTime> QAOMCHAINAPPROV { get; set; }
        public Nullable<System.DateTime> QNOPFCLETTERSUP { get; set; }
        public Nullable<System.DateTime> QPRESALECERTIFI { get; set; }
        public Nullable<System.DateTime> QSCRACERTIFICAT { get; set; }
        public Nullable<System.DateTime> QPUBAFFIDAVITRC { get; set; }
        public Nullable<System.DateTime> QSCHEDULEDPUBLI { get; set; }
        public Nullable<System.DateTime> QPUBAFFIDAVITUPLOAD { get; set; }
        public Nullable<System.DateTime> QHUDOCCLETTERUPLOAD1 { get; set; }
        public Nullable<System.DateTime> QHUDOCCLETTERUPLOAD2 { get; set; }
    }
}
