//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEAK_XMLImportProductMappings
    {
        public int ImportMapID { get; set; }
        public string ProductName { get; set; }
        public Nullable<bool> IsDIL { get; set; }
        public Nullable<bool> IsForeclosure { get; set; }
        public Nullable<bool> IsConveyance { get; set; }
        public Nullable<bool> IsSkipTrace { get; set; }
        public Nullable<bool> IsGAL { get; set; }
        public Nullable<bool> IsGAP { get; set; }
        public Nullable<bool> IsCommercial { get; set; }
    }
}
