//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProLawIntegrationEntities : DbContext
    {
        public ProLawIntegrationEntities()
            : base("name=ProLawIntegrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PEAK_XMLFileImports> PEAK_XMLFileImports { get; set; }
        public virtual DbSet<PEAK_XMLImportAttachmentLog> PEAK_XMLImportAttachmentLog { get; set; }
        public virtual DbSet<PEAK_XMLImportLog> PEAK_XMLImportLog { get; set; }
        public virtual DbSet<PEAK_XMLImportProductMappings> PEAK_XMLImportProductMappings { get; set; }
    }
}
