//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepositoryChangeLogs
    {
        public long RepositoryChangeLogId { get; set; }
        public string FQAType { get; set; }
        public string TableUpdated { get; set; }
        public string PrimaryKey { get; set; }
        public string ColumnUpdated { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> CommittedAt { get; set; }
        public Nullable<System.DateTime> ErrorAt { get; set; }
        public string ErrorNotes { get; set; }
    }
}
