//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationExternalProject_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProLawEntities : DbContext
    {
        public ProLawEntities()
            : base("name=ProLawEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Matters> Matters { get; set; }
        public virtual DbSet<MattersQFORECLOSUR5> MattersQFORECLOSUR5 { get; set; }
        public virtual DbSet<MattersQFORECLOSUR6> MattersQFORECLOSUR6 { get; set; }
        public virtual DbSet<MattersQFORECLOSUREPRO> MattersQFORECLOSUREPRO { get; set; }
    }
}
